name: Microsoft Security DevOps
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  msdevopssec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Microsoft Security DevOps
        uses: microsoft/msdevopssec@v0
        with:
          # The name of your Azure subscription where you have onboarded to Microsoft Defender for Cloud.
          subscriptionName: ''
          # The name of your environment that you have onboarded to Microsoft Defender for Cloud.
          environmentName: ''
